# Generated by Django 3.0 on 2019-12-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='Album Not Found', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.CharField(default='URL Not Found', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='Title Not Found', max_length=255),
        ),
    ]
